/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robert_ds.crsystem.employeeGUI;
import com.robert_ds.crsystem.employeeBL.employeesBL;
import com.robert_ds.crsystem.employeeDAL.Connect;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robert
 */
public class frmEmployees extends javax.swing.JFrame {
  
    DefaultTableModel model;

    /**
     * Creates new form frmEmployees
     */
    public frmEmployees() {
        initComponents();
              
        String[] titles = {"Id", "Name", "Mail"};
        
        model = new DefaultTableModel(null, titles);
        tblEmployees.setModel(model);
        
        this.showData();
        this.cleanInputs();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblEmployees = new javax.swing.JTable();
    addBtn = new javax.swing.JButton();
    delBtn = new javax.swing.JButton();
    editBtn = new javax.swing.JButton();
    cancelBtn = new javax.swing.JButton();
    txtID = new javax.swing.JTextField();
    txtName = new javax.swing.JTextField();
    txtMail = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Employee System");
    setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    setFocusable(false);
    setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
    setIconImages(getIconImages());
    setResizable(false);

    tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblEmployeesMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tblEmployees);

    addBtn.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
    addBtn.setIcon(new javax.swing.ImageIcon("/home/robert/Files/Projects/All Projects Code/Java/crsystem/src/main/resources/imgs/user-plus-solid-24.png")); // NOI18N
    addBtn.setText("Add");
    addBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addBtnActionPerformed(evt);
      }
    });

    delBtn.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
    delBtn.setIcon(new javax.swing.ImageIcon("/home/robert/Files/Projects/All Projects Code/Java/crsystem/src/main/resources/imgs/user-minus-regular-24.png")); // NOI18N
    delBtn.setText("Del");
    delBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delBtnActionPerformed(evt);
      }
    });

    editBtn.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
    editBtn.setIcon(new javax.swing.ImageIcon("/home/robert/Files/Projects/All Projects Code/Java/crsystem/src/main/resources/imgs/edit-alt-solid-24.png")); // NOI18N
    editBtn.setText("Edit");
    editBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editBtnActionPerformed(evt);
      }
    });

    cancelBtn.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
    cancelBtn.setIcon(new javax.swing.ImageIcon("/home/robert/Files/Projects/All Projects Code/Java/crsystem/src/main/resources/imgs/checkbox-solid-24.png")); // NOI18N
    cancelBtn.setText("Cancel");
    cancelBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelBtnActionPerformed(evt);
      }
    });

    txtID.setEditable(false);
    txtID.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

    txtName.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

    txtMail.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

    jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
    jLabel1.setIcon(new javax.swing.ImageIcon("/home/robert/Files/Projects/All Projects Code/Java/crsystem/src/main/resources/imgs/child-regular-24.png")); // NOI18N
    jLabel1.setText("Employee System");
    jLabel1.setName(""); // NOI18N

    jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel2.setText("ID:");

    jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel3.setText("Name:");

    jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel4.setText("Mail:");

    jMenu1.setText("File");
    jMenu1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

    jMenuItem1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
    jMenuItem1.setText("exit");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
          .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(54, 54, 54)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(delBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(44, 44, 44)
            .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(53, 53, 53)
            .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(14, 14, 14))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(txtName)
              .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
              .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(70, 70, 70))))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(183, 183, 183))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addComponent(addBtn)
            .addComponent(editBtn)
            .addComponent(cancelBtn))
          .addComponent(delBtn))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Method that click in button add save data on database
     * @param evt 
     */
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        Connect objConnect = new Connect();
        employeesBL objEmployees = catchGuiData();
        
        String strSqlInsert = String.format("INSERT INTO Employees(name,mail)" + " VALUES ('%s','%s')", objEmployees.getName(), objEmployees.getMail());

        
        objConnect.sqlInsertion(strSqlInsert);
        
        try {
        ResultSet result = objConnect.queryRegistres("SELECT * FROM Employees");
        
        while(result.next()) {
          System.out.println(result.getString("id"));
          System.out.println(result.getString("name"));
          System.out.println(result.getString("mail"));
        }
        
      } catch (Exception e) {
          System.out.println("Exception: " +  e);
      }
        
      this.showData();
      this.cleanInputs();
        
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * Method that click on one element of table show data on inputs
     * @param evt 
     */
  private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
    // TODO add your handling code here:
    
    if(evt.getClickCount() == 1) {
      JTable recept = (JTable)evt.getSource();
      txtID.setText(recept.getModel().getValueAt(recept.getSelectedRow(),0).toString());
      txtName.setText(recept.getModel().getValueAt(recept.getSelectedRow(),1).toString());
      txtMail.setText(recept.getModel().getValueAt(recept.getSelectedRow(),2).toString());
    }
    
    addBtn.setEnabled(false);
    delBtn.setEnabled(true);
    editBtn.setEnabled(true);
    
  }//GEN-LAST:event_tblEmployeesMouseClicked

  /**
   * Method that delete data of table and database
   * @param evt 
   */
  private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
    // TODO add your handling code here:
     Connect objConnect = new Connect();
        employeesBL objEmployees = catchGuiData();
        
        String strSqlInsert = String.format("DELETE FROM Employees WHERE Id = %d", objEmployees.getID());

        
        objConnect.sqlInsertion(strSqlInsert);
        this.showData();
        this.cleanInputs();
  }//GEN-LAST:event_delBtnActionPerformed

  /**
   * Method edit information
   * @param evt 
   */
  private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
    // TODO add your handling code here:
    Connect objConnect = new Connect();
    employeesBL objEmployees = catchGuiData();
        
        String strSqlInsert = String.format("UPDATE Employees SET name = '%s', mail = '%s' WHERE Id = %d ", objEmployees.getName(), objEmployees.getMail(), objEmployees.getID());

        
        objConnect.sqlInsertion(strSqlInsert);
        this.showData();
        this.cleanInputs();
  }//GEN-LAST:event_editBtnActionPerformed

  /**
   * Method cancel add or edit user
   * @param evt 
   */
  private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
    // TODO add your handling code here:
    this.cleanInputs();
  }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * Method that show data to database on table
     */
    public void showData() {
      
      // Clean table before delete row
      while(model.getRowCount() > 0) {
        model.removeRow(0);
      }
      
       Connect objConnect = new Connect();
       
      try {
        ResultSet result = objConnect.queryRegistres("SELECT * FROM Employees");
        
        while(result.next()) {
          System.out.println(result.getString("id"));
          System.out.println(result.getString("name"));
          System.out.println(result.getString("mail"));
          
          Object[] objUser = {result.getString("id"),result.getString("name"),result.getString("mail")};
          
          model.addRow(objUser);
          
        }
        
      } catch (Exception e) {
          System.out.println("Exception: " +  e);
      }
    }
        
    /**
     * Method Catch values of GUI
     * @return objEmployees
     */
    public employeesBL catchGuiData() {
      employeesBL objEmployees = new employeesBL();
      
      int ID = (txtID.getText().isEmpty()) ? 0 : Integer.parseInt(txtID.getText());
      objEmployees.setID(ID);
      
      objEmployees.setName(txtName.getText());
      objEmployees.setMail(txtMail.getText());
      
      return objEmployees;
    }
    
    public void cleanInputs() {
      txtID.setText("");
      txtName.setText("");
      txtMail.setText("");
      
      addBtn.setEnabled(true);
      delBtn.setEnabled(false);
      editBtn.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployees().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addBtn;
  private javax.swing.JButton cancelBtn;
  private javax.swing.JButton delBtn;
  private javax.swing.JButton editBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblEmployees;
  private javax.swing.JTextField txtID;
  private javax.swing.JTextField txtMail;
  private javax.swing.JTextField txtName;
  // End of variables declaration//GEN-END:variables
}
