/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robert_ds.crsystem.employeeGUI;
import com.robert_ds.crsystem.employeeBL.employeesBL;
import com.robert_ds.crsystem.employeeDAL.Connect;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robert
 */
public class frmEmployees extends javax.swing.JFrame {
  
  int xMouse;
  int yMouse;
  
    DefaultTableModel model;

    /**
     * Creates new form frmEmployees
     */
    public frmEmployees() {
        initComponents();
              
        String[] titles = {"Id", "Name", "Mail"};
        
        model = new DefaultTableModel(null, titles);
        tblEmployees.setModel(model);
        
        this.showData();
        this.cleanInputs();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblEmployees = new javax.swing.JTable();
    txtID = new javax.swing.JTextField();
    txtName = new javax.swing.JTextField();
    txtMail = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    HeaderPanel = new javax.swing.JPanel();
    closeButton = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    addBtn = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    delBtn = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    editBtn = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    cancelBtn = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Employee System");
    setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    setFocusable(false);
    setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
    setIconImages(getIconImages());
    setUndecorated(true);
    setResizable(false);

    jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    tblEmployees.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
    tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblEmployeesMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tblEmployees);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 508, 200));

    txtID.setEditable(false);
    txtID.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
    jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 72, 34, 30));

    txtName.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
    txtName.setBorder(null);
    txtName.setPreferredSize(new java.awt.Dimension(64, 15));
    jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 301, 30));

    txtMail.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
    txtMail.setBorder(null);
    txtMail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    txtMail.setMinimumSize(new java.awt.Dimension(64, 15));
    jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 301, 30));

    jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/child-regular-24.png"))); // NOI18N
    jLabel1.setText("Employee System");
    jLabel1.setName(""); // NOI18N
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 520, -1));

    jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel2.setText("ID:");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

    jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel3.setText("Name:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

    jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel4.setText("Mail:");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

    HeaderPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    HeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseDragged(java.awt.event.MouseEvent evt) {
        HeaderPanelMouseDragged(evt);
      }
    });
    HeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        HeaderPanelMousePressed(evt);
      }
    });

    closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/x-square-solid-24.png"))); // NOI18N
    closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        closeButtonMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
    HeaderPanel.setLayout(HeaderPanelLayout);
    HeaderPanelLayout.setHorizontalGroup(
      HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
        .addGap(0, 499, Short.MAX_VALUE)
        .addComponent(closeButton))
    );
    HeaderPanelLayout.setVerticalGroup(
      HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jPanel1.add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    jPanel2.setBackground(new java.awt.Color(255, 255, 204));

    addBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    addBtn.setForeground(new java.awt.Color(255, 153, 0));
    addBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user-plus-solid-24.png"))); // NOI18N
    addBtn.setText("Add");
    addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        addBtnMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

    jPanel3.setBackground(new java.awt.Color(255, 255, 204));

    delBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    delBtn.setForeground(new java.awt.Color(255, 153, 0));
    delBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user-minus-regular-24.png"))); // NOI18N
    delBtn.setText("Del");
    delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        delBtnMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(delBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(delBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

    jPanel4.setBackground(new java.awt.Color(255, 255, 204));

    editBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    editBtn.setForeground(new java.awt.Color(255, 153, 0));
    editBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/edit-alt-solid-24.png"))); // NOI18N
    editBtn.setText("Edit");
    editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        editBtnMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(editBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

    jPanel5.setBackground(new java.awt.Color(255, 255, 204));

    cancelBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    cancelBtn.setForeground(new java.awt.Color(255, 153, 0));
    cancelBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/checkbox-solid-24.png"))); // NOI18N
    cancelBtn.setText("Cancel");
    cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        cancelBtnMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that click on one element of table show data on inputs
     * @param evt 
     */
  private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
    // TODO add your handling code here:
    
    if(evt.getClickCount() == 1) {
      JTable recept = (JTable)evt.getSource();
      txtID.setText(recept.getModel().getValueAt(recept.getSelectedRow(),0).toString());
      txtName.setText(recept.getModel().getValueAt(recept.getSelectedRow(),1).toString());
      txtMail.setText(recept.getModel().getValueAt(recept.getSelectedRow(),2).toString());
    }
    
    addBtn.setEnabled(false);
    delBtn.setEnabled(true);
    editBtn.setEnabled(true);
    
  }//GEN-LAST:event_tblEmployeesMouseClicked

  /**
   * Method that close app
   * @param evt 
   */
  private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
    System.exit(0);
  }//GEN-LAST:event_closeButtonMouseClicked

  /**
   * Method get position pressed header panel
   * @param evt 
   */
  private void HeaderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMousePressed
    xMouse = evt.getX();
    yMouse = evt.getY();
  }//GEN-LAST:event_HeaderPanelMousePressed

  private void HeaderPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
  }//GEN-LAST:event_HeaderPanelMouseDragged

  /**
     * Method that click in button add save data on database
     * @param evt 
     */
  private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
    Connect objConnect = new Connect();
    employeesBL objEmployees = catchGuiData();

    String strSqlInsert = String.format("INSERT INTO Employees(name,mail)" + " VALUES ('%s','%s')", objEmployees.getName(), objEmployees.getMail());

    objConnect.sqlInsertion(strSqlInsert);

    try {
      ResultSet result = objConnect.queryRegistres("SELECT * FROM Employees");

      while(result.next()) {
        //          System.out.println(result.getString("id"));
        //          System.out.println(result.getString("name"));
        //          System.out.println(result.getString("mail"));
      }

    } catch (Exception e) {
      System.out.println("Exception: " +  e);
    }

    this.showData();
    this.cleanInputs();
  }//GEN-LAST:event_addBtnMouseClicked

   /**
   * Method that delete data of table and database
   * @param evt 
   */
  private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
    Connect objConnect = new Connect();
    employeesBL objEmployees = catchGuiData();

    String strSqlInsert = String.format("DELETE FROM Employees WHERE Id = %d", objEmployees.getID());

    objConnect.sqlInsertion(strSqlInsert);
    this.showData();
    this.cleanInputs();                    
    
  }//GEN-LAST:event_delBtnMouseClicked

   /**
   * Method edit information
   * @param evt 
   */
  private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
    Connect objConnect = new Connect();
    employeesBL objEmployees = catchGuiData();

    String strSqlInsert = String.format("UPDATE Employees SET name = '%s', mail = '%s' WHERE Id = %d ", objEmployees.getName(), objEmployees.getMail(), objEmployees.getID());

    objConnect.sqlInsertion(strSqlInsert);
    this.showData();
    this.cleanInputs();  
    
  }//GEN-LAST:event_editBtnMouseClicked

  private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
    this.cleanInputs();
  }//GEN-LAST:event_cancelBtnMouseClicked
              
    /**
     * Method that show data to database on table
     */
    public void showData() {
      
      // Clean table before delete row
      while(model.getRowCount() > 0) {
        model.removeRow(0);
      }
      
       Connect objConnect = new Connect();
       
      try {
        ResultSet result = objConnect.queryRegistres("SELECT * FROM Employees");
        
        while(result.next()) {
//          System.out.println(result.getString("id"));
//          System.out.println(result.getString("name"));
//          System.out.println(result.getString("mail"));
          
          Object[] objUser = {result.getString("id"),result.getString("name"),result.getString("mail")};
          
          model.addRow(objUser);
          
        }
        
      } catch (Exception e) {
          System.out.println("Exception: " +  e);
      }
    }
        
    /**
     * Method Catch values of GUI
     * @return objEmployees
     */
    public employeesBL catchGuiData() {
      employeesBL objEmployees = new employeesBL();
      
      int ID = (txtID.getText().isEmpty()) ? 0 : Integer.parseInt(txtID.getText());
      objEmployees.setID(ID);
      
      objEmployees.setName(txtName.getText());
      objEmployees.setMail(txtMail.getText());
      
      return objEmployees;
    }
    
    public void cleanInputs() {
      txtID.setText("");
      txtName.setText("");
      txtMail.setText("");
      
      addBtn.setEnabled(true);
      delBtn.setEnabled(false);
      editBtn.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployees().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel HeaderPanel;
  private javax.swing.JLabel addBtn;
  private javax.swing.JLabel cancelBtn;
  private javax.swing.JLabel closeButton;
  private javax.swing.JLabel delBtn;
  private javax.swing.JLabel editBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblEmployees;
  private javax.swing.JTextField txtID;
  private javax.swing.JTextField txtMail;
  private javax.swing.JTextField txtName;
  // End of variables declaration//GEN-END:variables
}
